#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/bernhard/Downloads/nrn-7.3-build"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/bernhard/Downloads/nrn-7.3-build/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/bernhard/workspace/olfactory_system/OlfactorySystem/neuron_files/x86_64/.libs/libnrnmech.so" "$@"
